name: release-win7-legacy

on:
  push:
    branches:
      - feat/win7-legacy
    tags:
      - "*-legacy7"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  debug:
    name: debug
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Print context
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
          echo "ref_name=${{ github.ref_name }}"
          echo "head_branch=${{ github.head_ref }}"
          echo "head_sha=${{ github.sha }}"
          echo "RunId=${{ github.run_id }}"
      - name: True
        run: echo "yes"
